# THIS IS A COMMENT
print("Hello,")
print("Good morning!")  # THIS IS ALSO A COMMENT

# println("THIS STATEMENT WON'T BE EXECUTED")

# RUN THE SCRIPT USING CELL
#%%
print("Hello World");
#%%

# RUN THE SCRIPT USING TERMINAL
# python main

# MULTI-LINE COMMENT
''''
THIS IS A MULTI-LINE COMMENT
print("THIS STATEMENT WON'T BE EXECUTED")
'''

# MULTI-LINE COMMENT CAN WRITTEN IN A SINGLE LINE
'''' THIS IS A MULTI-LINE COMMENT IN A SINGLE LINE '''

